CLASS Z_GIT_TEST_APP DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z_GIT_TEST_APP IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.
    out->write( 'Hello World from D82' ).
  ENDMETHOD.
ENDCLASS.
